name = "tt-tournament"
compatibility_date = "2025-01-01"
pages_build_output_dir = ".output/public"

# KV namespace for caching
[[kv_namespaces]]
binding = "KV"
id = "87626bd6044e4e6a977e2ae1a5f6f07a"
preview_id = "87626bd6044e4e6a977e2ae1a5f6f07a"

# Environment variables (set in Cloudflare dashboard for production)
[vars]
CACHE_TTL = "600"
